source ~/dotfiles/common/bashrc
alias vi=/home/hikalium/bin/nvim.appimage
alias vim=/home/hikalium/bin/nvim.appimage
alias nvim=/home/hikalium/bin/nvim.appimage

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export RA_LOG_STDERR=/tmp/ra.log
eval `ssh-agent`
[ -f $HOME/.cargo/env ] && . "$HOME/.cargo/env"
